# Generated by Django 6.0.2 on 2026-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('DOCTOR', 'Medical Practitioner'), ('PATIENT', 'Patient')], default='PATIENT', max_length=10),
        ),
    ]
