# Generated by Django 6.0.2 on 2026-04-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('DOCTOR', 'DOCTOR'), ('PATIENT', 'Patient')], max_length=10),
        ),
    ]
