# Generated by Django 6.0.2 on 2026-04-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('DOCTOR', 'DOCTOR'), ('PATIENT', 'Patient')], max_length=10),
        ),
    ]
