# Generated by Django 6.0.2 on 2026-04-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_medicalrecord_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='records.medicalrecord')),
            ],
        ),
    ]
