# Generated by Django 6.0.2 on 2026-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_aianalysisrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
