# Generated by Django 6.0.2 on 2026-04-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_medicalrecord_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='ai_diagnosis_notes',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='is_flagged_by_ai',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AIAnalysisRecord',
        ),
    ]
