# Generated by Django 6.0.2 on 2026-04-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_remove_medicalrecord_ai_diagnosis_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ai_confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_glucose',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_pressure_sys',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='heart_rate',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='needs_advanced_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='oxygen_saturation',
            field=models.IntegerField(default=98),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=36.5, max_digits=4),
        ),
    ]
