# Generated by Django 6.0.2 on 2026-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_medicalrecord_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='blood_pressure_sys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
