# Generated by Django 6.0.2 on 2026-03-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='nhif_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NHIF Number'),
        ),
    ]
